apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: smartevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
      - name: admin-service
        image: admin-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8084
        env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://db.clngjxlkalfnmwnggnxz.supabase.co:6543/postgres?currentSchema=admin_schema"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres.clngjxlkalfnmwnggnxz"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "hatimBH12345@"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
              value: "admin_schema"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "admin-service"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
