apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  namespace: smartevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
      - name: interaction-service
        image: development-platform-team_b20-interaction-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://db.clngjxlkalfnmwnggnxz.supabase.co:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres.clngjxlkalfnmwnggnxz"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "hatimBH12345@"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
          value: "interactions_schema"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
