apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: smartevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: development-platform-team_b20-recommendation-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://db.clngjxlkalfnmwnggnxz.supabase.co:5432/postgres"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres.clngjxlkalfnmwnggnxz"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "hatimBH12345@"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
          value: "recommendation_schema"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
