apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-service
  namespace: smartevent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - name: recommendation-service
        image: recommendation-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&currentSchema=recommendation_schema"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres.clngjxlkalfnmwnggnxz"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "hatimBH12345@"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://discovery-server:8761/eureka/"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "recommendation-service"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
