---
- name: Check kubectl via minikube
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- version --client'
  register: kubectl_version
  changed_when: false
  ignore_errors: yes

- name: Display kubectl version
  debug:
    msg: "{{ kubectl_version.stdout }}"

- name: Check minikube status
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" status'
  register: minikube_status
  changed_when: false
  ignore_errors: yes

- name: Display minikube status
  debug:
    msg: "{{ minikube_status.stdout }}"

- name: Start minikube if not running
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" start --driver=docker'
  when: "'Running' not in minikube_status.stdout"
  ignore_errors: yes