apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: smartevent
data:
  # URLs Eureka
  EUREKA_URI: "http://discovery-server:8761/eureka/"
  
  # Base de données (hostname = postgres service)
  DB_HOST: "postgres"
  DB_NAME: "smartevent"
  DB_PORT: "5432"
  
  # URLs complètes pour Spring
  
  # Schémas par service
  USER_SCHEMA: "users"
  EVENT_SCHEMA: "events"
  INTERACTION_SCHEMA: "interactions"
  ADMIN_SCHEMA: "admin"
  
  # Logging
  LOGGING_LEVEL_ROOT: "INFO"
