apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smartevent-ingress
  namespace: smartevent
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: smartevent.local
    http:
      paths:
      # Frontend - page d'accueil
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 3000
      # API Gateway - tous les appels API
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080
      # Eureka - découverte des services
      - path: /eureka
        pathType: Prefix
        backend:
          service:
            name: discovery-server
            port:
              number: 8761
