apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: smartevent
type: Opaque
data:
  # postgres (en base64)
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres (en base64)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # 5432 (en base64)
  DB_PORT: NTQzMg==
