apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: smartevent
type: Opaque
data:
  # Encoder en base64 :
  # echo -n "valeur" | base64

  db-url: amRiYzpwb3N0Z3Jlc3FsOi8vZGIuY2xuZ2p4bGthbGZubXduZ2dueHouc3VwYWJhc2UuY286NTQzMi9wb3N0Z3Jlcw==
  # = jdbc:postgresql://db.clngjxlkalfnmwnggnxz.supabase.co:5432/postgres

  db-username: cG9zdGdyZXMuY2xuZ2p4bGthbGZubXduZ2dueHo=
  # = postgres.clngjxlkalfnmwnggnxz

  db-password: aGF0aW1CSjEyMzQ1QA==
  # = hatimBH12345@