---
- name: Apply namespace
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/namespace.yaml"'

- name: Apply configmap
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/configmap.yaml"'

- name: Apply secrets
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/secret.yaml"'

- name: Apply deployments
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/deployment/"'

- name: Apply services
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/service/"'

- name: Apply ingress
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- apply -f "C:/Users/LENOVO/Desktop/smart-social-event-organizer/kubernetes/base/ingress.yaml"'

- name: Check all pods status
  shell: '"/mnt/c/Program Files/Kubernetes/Minikube/minikube.exe" kubectl -- get pods -n smartevent'
  register: pods_status

- name: Display pods status
  debug:
    msg: "{{ pods_status.stdout }}"