# 1. URL JDBC
spring.datasource.url=jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:5432/postgres?sslmode=require

spring.datasource.username=postgres.clngjxlkalfnmwnggnxz

spring.datasource.password=hatimBH12345@

# 4. Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# 5. Réglage Hibernate 
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true