apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: smartevent
spec:
  selector:
    app: recommendation-service
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP